name: Compile TinyWM for R36S
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install ARM64 Cross-Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Compile static binary
        run: |
          aarch64-linux-gnu-gcc tinywm.c -o tinywm_bin -static -O2

      - name: Upload compiled binary to GitHub Releases
        uses: actions/upload-artifact@v4
        with:
          name: tinywm-for-r36s
          path: tinywm_bin
