name: Compile TinyWM for R36S
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install ARM64 Cross-Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu wget

      - name: Download and Extract ARM64 X11 Libraries Direct
        run: |
          mkdir -p local_x11
          cd local_x11
          # Скачиваем чистые официальные пакеты библиотек ARM64 (Ubuntu Ports)
          wget -q http://ubuntu.com
          wget -q http://ubuntu.com
          wget -q http://ubuntu.com
          wget -q http://ubuntu.com
          wget -q http://ubuntu.com
          # Распаковываем их как архивы прямо в нашу рабочую папку в облаке
          for f in *.deb; do dpkg-deb -x "$f" . ; done

      - name: Compile static binary using precise paths
        run: |
          aarch64-linux-gnu-gcc tinywm.c -o tinywm_bin -static -O2 \
            -I./local_x11/usr/include \
            -L./local_x11/usr/lib/aarch64-linux-gnu \
            -lX11 -lxcb -lXau -lXdmcp
          
      - name: Upload compiled binary to GitHub Releases
        uses: actions/upload-artifact@v4
        with:
          name: tinywm-for-r36s
          path: tinywm_bin
